import 'dart:convert';

import '../models/models.dart';
import 'curl.dart';

/// Builds a shareable Markdown document from a request + its response,
/// for API documentation. Secrets (Authorization, API keys) are masked.
String buildMarkdownDoc(RequestModel r, ResponseData res) {
  final b = StringBuffer();
  final title = r.name == 'Untitled request' ? r.url : r.name;
  b.writeln('# $title\n');
  b.writeln('**${r.method.toUpperCase()}** `${r.url}`\n');
  if (res.error == null) {
    b.writeln('`${res.statusCode} ${res.statusMessage}` · '
        '${res.durationMs} ms · ${res.sizeBytes} bytes\n');
  } else {
    b.writeln('> Request failed: ${res.error}\n');
  }

  b.writeln('## Request\n');
  final params = r.params.where((p) => p.enabled && p.key.isNotEmpty).toList();
  if (params.isNotEmpty) {
    b.writeln('### Query parameters\n');
    b.writeln('| Name | Value |\n|---|---|');
    for (final p in params) {
      b.writeln('| ${_cell(p.key)} | ${_cell(p.value)} |');
    }
    b.writeln();
  }

  final headers = r.headers.where((h) => h.enabled && h.key.isNotEmpty).toList();
  final authLine = switch (r.authType) {
    AuthType.bearer => 'Authorization: Bearer $_mask',
    AuthType.basic => 'Authorization: Basic $_mask',
    AuthType.apiKey when r.apiKeyInHeader && r.apiKeyName.isNotEmpty =>
      '${r.apiKeyName}: $_mask',
    _ => null,
  };
  if (headers.isNotEmpty || authLine != null) {
    b.writeln('### Headers\n');
    b.writeln('| Name | Value |\n|---|---|');
    for (final h in headers) {
      final masked = h.key.toLowerCase() == 'authorization' ||
          h.key.toLowerCase().contains('api-key') ||
          h.key.toLowerCase() == 'x-api-key';
      b.writeln('| ${_cell(h.key)} | ${masked ? _mask : _cell(h.value)} |');
    }
    if (authLine != null) {
      final i = authLine.indexOf(': ');
      b.writeln(
          '| ${_cell(authLine.substring(0, i))} | ${authLine.substring(i + 2)} |');
    }
    b.writeln();
  }

  if (r.bodyType != BodyType.none) {
    b.writeln('### Body (${r.bodyType.label})\n');
    if (r.bodyType == BodyType.formUrlEncoded) {
      b.writeln('| Field | Value |\n|---|---|');
      for (final f in r.formFields.where((f) => f.enabled && f.key.isNotEmpty)) {
        b.writeln('| ${_cell(f.key)} | ${_cell(f.value)} |');
      }
      b.writeln();
    } else {
      final lang = switch (r.bodyType) {
        BodyType.json => 'json',
        BodyType.xml => 'xml',
        BodyType.graphql => 'graphql',
        _ => '',
      };
      b.writeln('```$lang\n${r.body}\n```\n');
      if (r.bodyType == BodyType.graphql &&
          r.graphqlVariables.trim().isNotEmpty) {
        b.writeln('GraphQL variables:\n');
        b.writeln('```json\n${r.graphqlVariables}\n```\n');
      }
    }
  }

  b.writeln('### cURL\n');
  b.writeln('```sh\n${toCurl(_masked(r))}\n```\n');

  if (res.error == null) {
    b.writeln('## Response\n');
    if (res.headers.isNotEmpty) {
      b.writeln('### Headers\n');
      b.writeln('| Name | Value |\n|---|---|');
      final entries = res.headers.entries.toList()
        ..sort((a, b) => a.key.compareTo(b.key));
      for (final e in entries) {
        b.writeln('| ${_cell(e.key)} | ${_cell(e.value.join(', '))} |');
      }
      b.writeln();
    }
    b.writeln('### Body\n');
    var body = res.bodyText;
    try {
      body = const JsonEncoder.withIndent('  ').convert(jsonDecode(body));
    } catch (_) {}
    const cap = 200 * 1024;
    final truncated = body.length > cap;
    if (truncated) body = body.substring(0, cap);
    final isJson = (res.contentType ?? '').contains('json');
    b.writeln('```${isJson ? 'json' : ''}\n${body.isEmpty ? '(empty)' : body}\n```');
    if (truncated) b.writeln('\n_Body truncated at 200 KB._');
  }

  b.writeln('\n---\n_Generated by ApiWorkbench on '
      '${DateTime.now().toString().substring(0, 16)}._');
  return b.toString();
}

const _mask = '••••••';

/// Copy of the request with secrets removed so the cURL block is shareable.
RequestModel _masked(RequestModel r) {
  final c = r.clone();
  if (c.bearerToken.isNotEmpty) c.bearerToken = _mask;
  if (c.basicPassword.isNotEmpty) c.basicPassword = _mask;
  if (c.apiKeyValue.isNotEmpty) c.apiKeyValue = _mask;
  for (final h in c.headers) {
    if (h.key.toLowerCase() == 'authorization' ||
        h.key.toLowerCase().contains('api-key') ||
        h.key.toLowerCase() == 'x-api-key') {
      h.value = _mask;
    }
  }
  return c;
}

String _cell(String s) =>
    s.replaceAll('|', r'\|').replaceAll('\n', ' ');
